name: Terraform plan/apply

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
     - create-s3/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'delply to aws'
    runs-on: ubuntu-latest
    environment: deploy-to-aws

    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4.1.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        role-to-assume: arn:aws:iam::539247452778:role/admin-access
        role-session-name: admin-access
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0

    - name: Terraform Initialize
      working-directory: private-access-to-ec2
      run: terraform init

    - name: Terraform Format
      working-directory: private-access-to-ec2
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: private-access-to-ec2
      run: terraform validate

    - name: Terraform Plan
      working-directory: private-access-to-ec2
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: private-access-to-ec2
      run: terraform apply -auto-approve

    - name: Print Assumed Role
      run: aws sts get-caller-identity